--- STEAMODDED HEADER
--- MOD_NAME: naneinf Practice Decks
--- MOD_ID: naneinfPracticeDecks
--- MOD_AUTHOR: [GamingMeister]
--- MOD_DESCRIPTION: Adds decks that use the Plasma Deck scoring & scaling, but filter out as many jokers, consumables, tags, & vouchers as possible, to make unseeded naneinf runs much easier to obtain (mostly meant for practicing White Stake Plasma Deck unseeded naneinf runs).
--- DEPENDENCIES: [Steamodded>=1.0.0~BETA]
--- VERSION: 1.0.0-ALPHA


----------------------------------------------
------------MOD CODE -------------------------

-- Plasma balancing code mostly copy-pasted from back.lua (108). Due to the method being written poorly, this must be reinjected, but modified to only affect decks with "config.plasma_balancing = true"
local Backtrigger_effectRef = Back.trigger_effect
function Back:trigger_effect(args)

    -- Preserve original variable calculations to not break Plasma Deck
    local chips, mult = Backtrigger_effectRef(self, args)
    if not args then
        return chips, mult
    end
    -- Replace "name" == 'Plasma Deck' with a better version
    if self.effect.config.plasma_balancing and args.context == 'blind_amount' then
        return
    end
    -- Again here
    if self.effect.config.plasma_balancing and args.context == 'final_scoring_step' then
        local tot = args.chips + args.mult
        args.chips = math.floor(tot/2)
        args.mult = math.floor(tot/2)
        update_hand_text({delay = 0}, { mult = args.mult, chips = args.chips})

        G.E_MANAGER:add_event(Event({
            func = (function()
                local text = localize('k_balanced')
                play_sound('gong', 0.94, 0.3)
                play_sound('gong', 0.94*1.5, 0.2)
                play_sound('tarot1', 1.5)
                ease_colour(G.C.UI_CHIPS, {0.8, 0.45, 0.85, 1})
                ease_colour(G.C.UI_MULT, {0.8, 0.45, 0.85, 1})
                attention_text({
                    scale = 1.4, text = text, hold = 2, align = 'cm', offset = {x = 0,y = -2.7},major = G.play
                })

                G.E_MANAGER:add_event(Event({
                    trigger = 'after',
                    blockable = false,
                    blocking = false,
                    delay =  4.3,
                    func = (function()
                        ease_colour(G.C.UI_CHIPS, G.C.BLUE, 2)
                        ease_colour(G.C.UI_MULT, G.C.RED, 2)
                        return true
                    end)
                }))

                G.E_MANAGER:add_event(Event({
                    trigger = 'after',
                    blockable = false,
                    blocking = false,
                    no_delete = true,
                    delay =  6.3,
                    func = (function()
                        G.C.UI_CHIPS[1], G.C.UI_CHIPS[2], G.C.UI_CHIPS[3], G.C.UI_CHIPS[4] = G.C.BLUE[1], G.C.BLUE[2], G.C.BLUE[3], G.C.BLUE[4]
                        G.C.UI_MULT[1], G.C.UI_MULT[2], G.C.UI_MULT[3], G.C.UI_MULT[4] = G.C.RED[1], G.C.RED[2], G.C.RED[3], G.C.RED[4]
                        return true
                    end)
                }))
                return true
            end)
        }))
        delay(0.6)
        -- Preserve original variable calculations to not break Plasma Deck
        chips, mult = args.chips, args.mult
    end
    return chips, mult

end

-- Code we have to inject into the run directly right after deck is selected
local Backapply_to_runRef = Back.apply_to_run
function Back.apply_to_run(arg_56_0)
    Backapply_to_runRef(arg_56_0)

    -- Immediately ban all of the things in every deck's "config.ban_keys" table, so the game hasn't even loaded Tags yet
    --This is why the event is blocked out; method would would never ban the Tags if done within the Balatro event handler... :(
    --(Shop should not need a reload, as we have not yet instantiated it)
    if arg_56_0.effect.config.ban_keys then
        --[[    G.E_MANAGER:add_event(Event({
            blockable = false,
            blocking = true,
            func = function()    ]]
                print('Banning cards...')
                for _, v in ipairs(arg_56_0.effect.config.ban_keys) do
                    G.GAME.banned_keys[v.id] = true
                end
                print('DONE!')
                return true
            --[[    end
        }))    ]]
    end

end


------------ NANEINF DECK ------------

local naneinf = SMODS.Deck:new(
    "naneinf Deck",
    "naneinf",
    {
        ban_keys = {
            --- Jokers ---
            {id = 'j_joker'},
            {id = 'j_greedy_joker'},
            {id = 'j_lusty_joker'},
            {id = 'j_wrathful_joker'},
            {id = 'j_gluttenous_joker'},
            {id = 'j_jolly'},
            {id = 'j_zany'},
            {id = 'j_mad'},
            {id = 'j_crazy'},
            {id = 'j_droll'},
            {id = 'j_sly'},
            {id = 'j_wily'},
            {id = 'j_clever'},
            {id = 'j_devious'},
            {id = 'j_crafty'},
            {id = 'j_half'},
            {id = 'j_stencil'},
            {id = 'j_four_fingers'},
            --{id = 'j_mime'},
            --{id = 'j_credit_card'},
            {id = 'j_ceremonial'},
            {id = 'j_banner'},
            {id = 'j_mystic_summit'},
            {id = 'j_marble'},
            {id = 'j_loyalty_card'},
            {id = 'j_8_ball'},
            {id = 'j_misprint'},
            {id = 'j_dusk'},
            {id = 'j_raised_fist'},
            --{id = 'j_chaos'},
            {id = 'j_fibonacci'},
            {id = 'j_steel_joker'},
            --{id = 'j_scary_face'},
            {id = 'j_abstract'},
            --{id = 'j_delayed_grat'},
            {id = 'j_hack'},
            {id = 'j_pareidolia'},
            {id = 'j_gros_michel'},
            {id = 'j_even_steven'},
            {id = 'j_odd_todd'},
            {id = 'j_scholar'},
            --{id = 'j_business'},
            {id = 'j_supernova'},
            {id = 'j_ride_the_bus'},
            {id = 'j_space'},
            --{id = 'j_egg'},
            --{id = 'j_burglar'},
            {id = 'j_blackboard'},
            {id = 'j_runner'},
            --{id = 'j_ice_cream'},
            --{id = 'j_dna'},
            --{id = 'j_splash'},
            --{id = 'j_blue_joker'},
            --{id = 'j_sixth_sense'},
            {id = 'j_constellation'},
            {id = 'j_hiker'},
            --{id = 'j_faceless'},
            {id = 'j_green_joker'},
            {id = 'j_superposition'},
            --{id = 'j_todo_list'},
            {id = 'j_cavendish'},
            {id = 'j_card_sharp'},
            {id = 'j_red_card'},
            {id = 'j_madness'},
            {id = 'j_square'},
            {id = 'j_seance'},
            --{id = 'j_riff_raff'},
            {id = 'j_vampire'},
            {id = 'j_shortcut'},
            {id = 'j_hologram'},
            {id = 'j_vagabond'},
            --{id = 'j_baron'},
            {id = 'j_cloud_9'},
            --{id = 'j_rocket'},
            {id = 'j_obelisk'},
            --{id = 'j_midas_mask'},
            --{id = 'j_luchador'},
            --{id = 'j_photograph'},
            --{id = 'j_gift'},
            --{id = 'j_turtle_bean'},
            {id = 'j_erosion'},
            --{id = 'j_reserved_parking'},
            --{id = 'j_mail'},
            --{id = 'j_to_the_moon'},
            --{id = 'j_hallucination'},
            {id = 'j_fortune_teller'},
            --{id = 'j_juggler'},
            {id = 'j_drunkard'},
            {id = 'j_stone'},
            --{id = 'j_golden'},
            {id = 'j_lucky_cat'},
            {id = 'j_baseball'},
            {id = 'j_bull'},
            --{id = 'j_diet_cola'},
            --{id = 'j_trading'},
            {id = 'j_flash'},
            {id = 'j_popcorn'},
            {id = 'j_trousers'},
            {id = 'j_ancient'},
            {id = 'j_ramen'},
            {id = 'j_walkie_talkie'},
            {id = 'j_selzer'},
            {id = 'j_castle'},
            {id = 'j_smiley'},
            {id = 'j_campfire'},
            --{id = 'j_ticket'},
            {id = 'j_mr_bones'},
            {id = 'j_acrobat'},
            --{id = 'j_sock_and_buskin'},
            {id = 'j_swashbuckler'},
            --{id = 'j_troubadour'},
            {id = 'j_certificate'},
            {id = 'j_smeared'},
            {id = 'j_throwback'},
            --{id = 'j_hanging_chad'},
            --{id = 'j_rough_gem'},
            --{id = 'j_bloodstone'},
            --{id = 'j_arrowhead'},
            {id = 'j_onyx_agate'},
            {id = 'j_glass'},
            --{id = 'j_ring_master'}, --Showman
            {id = 'j_flower_pot'},
            --{id = 'j_blueprint'},
            {id = 'j_wee'},
            {id = 'j_merry_andy'},
            --{id = 'j_oops'},
            --{id = 'j_idol'},
            {id = 'j_seeing_double'},
            {id = 'j_matador'},
            {id = 'j_hit_the_road'},
            {id = 'j_duo'},
            {id = 'j_trio'},
            {id = 'j_family'},
            {id = 'j_order'},
            {id = 'j_tribe'},
            {id = 'j_stuntman'},
            --{id = 'j_invisible'},
            --{id = 'j_brainstorm'},
            {id = 'j_satellite'},
            {id = 'j_shoot_the_moon'},
            {id = 'j_drivers_license'},
            --{id = 'j_cartomancer'},
            {id = 'j_astronomer'},
            {id = 'j_burnt'},
            {id = 'j_bootstraps'},
            {id = 'j_caino'},
            --{id = 'j_triboulet'},
            {id = 'j_yorick'},
            {id = 'j_chicot'},
            --{id = 'j_perkeo'},
            --- Planet Cards ---
            {id = 'c_mercury'},
            --{id = 'c_venus'},
            --{id = 'c_earth'},
            --{id = 'c_mars'},
            --{id = 'c_jupiter'},
            {id = 'c_saturn'},
            {id = 'c_uranus'},
            {id = 'c_neptune'},
            --{id = 'c_pluto'},
            --{id = 'c_planet_x'},
            --{id = 'c_ceres'},
            --{id = 'c_eris'},
            --- Spectral Cards ---
            {id = 'c_familiar'},
            {id = 'c_grim'},
            {id = 'c_incantation'},
            --{id = 'c_talisman'},
            --{id = 'c_aura'},
            {id = 'c_wraith'},
            {id = 'c_sigil'},
            {id = 'c_ouija'},
            --{id = 'c_ectoplasm'},
            --{id = 'c_immolate'},
            --{id = 'c_ankh'},
            --{id = 'c_deja_vu'},
            {id = 'c_hex'},
            {id = 'c_trance'},
            --{id = 'c_medium'},
            --{id = 'c_cryptid'},
            --{id = 'c_soul'},
            --{id = 'c_black_hole'},
            --- Tags ---
            {id = 'tag_handy'},
            {id = 'tag_standard'},
            {id = 'tag_d_six'},
            --{id = 'tag_negative'},
            --{id = 'tag_investment'},
            {id = 'tag_holo'},
            --{id = 'tag_rare'},
            --{id = 'tag_voucher'},
            {id = 'tag_garbage'},
            {id = 'tag_foil'},
            {id = 'tag_buffoon'},
            --{id = 'tag_boss'},
            --{id = 'tag_ethereal'},
            {id = 'tag_orbital'},
            --{id = 'tag_charm'},
            {id = 'tag_skip'},
            {id = 'tag_top_up'},
            {id = 'tag_polychrome'},
            --{id = 'tag_juggle'},
            --{id = 'tag_double'},
            {id = 'tag_coupon'},
            {id = 'tag_economy'},
            {id = 'tag_uncommon'},
            {id = 'tag_meteor'},
            --- Tarot Cards ---
            --{id = 'c_fool'},
            --{id = 'c_magician'},
            {id = 'c_high_priestess'},
            {id = 'c_empress'},
            --{id = 'c_emperor'},
            {id = 'c_heirophant'},
            {id = 'c_lovers'},
            --{id = 'c_chariot'},
            {id = 'c_justice'},
            --{id = 'c_hermit'},
            {id = 'c_wheel_of_fortune'},
            --{id = 'c_strength'},
            --{id = 'c_hanged_man'},
            --{id = 'c_death'},
            --{id = 'c_temperance'},
            --{id = 'c_devil'},
            --{id = 'c_tower'},
            --{id = 'c_star'},
            {id = 'c_moon'},
            --{id = 'c_sun'},
            {id = 'c_judgement'},
            --{id = 'c_world'},
            --- Vouchers ---
            --{id = 'v_overstock_norm'},
            --{id = 'v_overstock_plus'},
            --{id = 'v_clearance_sale'},
            --{id = 'v_liquidation'},
            {id = 'v_hone'},
            {id = 'v_glow_up'},
            --{id = 'v_reroll_surplus'},
            --{id = 'v_reroll_glut'},
            --{id = 'v_crystal_ball'},
            --{id = 'v_omen_globe'},
            --{id = 'v_telescope'},
            --{id = 'v_observatory'},
            --{id = 'v_grabber'},
            --{id = 'v_nacho_tong'},
            --{id = 'v_wasteful'},
            --{id = 'v_recyclomancy'},
            {id = 'v_tarot_merchant'},
            {id = 'v_tarot_tycoon'},
            {id = 'v_planet_merchant'},
            {id = 'v_planet_tycoon'},
            --{id = 'v_seed_money'},
            --{id = 'v_money_tree'},
            --{id = 'v_blank'},
            --{id = 'v_antimatter'},
            {id = 'v_magic_trick'},
            --- BREAK HERE ---
            {id = 'v_illusion'}
            --{id = 'v_hieroglyph'},
            --{id = 'v_petroglyph'},
            --{id = 'v_directors_cut'},
            --{id = 'v_retcon'},
            --{id = 'v_paint_brush'},
            --{id = 'v_palette'},
        },
        ante_scaling = 2,
        -- Use custom config here
        plasma_balancing = true
    },
    -- Ununsed Half-Plasma Half-Blue(?) cardback
    {x = 5, y = 2},
    {
        ["name"] = "naneinf Deck",
        ["text"] = {
            [1] = "Balance {C:chips}Chips{} and {C:mult}Mult{} when calculating",
            [2] = "score for played hand | {C:red}X2{} base Blind size",
            [3] = "{X:chips,C:white}Many{} \"useless\"",
            [4] = "{C:uncommon}Jokers{}, {C:tarot}Consumables{}, {C:attention}Tags{} and {C:attention}Vouchers{}",
            [5] = "are banned, easing unseeded naneinf practice"
        }
    }
)
naneinf:register()

------------ NANEINF+ DECK ------------

local naneinfplus = SMODS.Deck:new(
    "naneinf+ Deck",
    "naneinfplus",
    {
        ban_keys = {
            --- Jokers ---
            {id = 'j_joker'},
            {id = 'j_greedy_joker'},
            {id = 'j_lusty_joker'},
            {id = 'j_wrathful_joker'},
            {id = 'j_gluttenous_joker'},
            {id = 'j_jolly'},
            {id = 'j_zany'},
            {id = 'j_mad'},
            {id = 'j_crazy'},
            {id = 'j_droll'},
            {id = 'j_sly'},
            {id = 'j_wily'},
            {id = 'j_clever'},
            {id = 'j_devious'},
            {id = 'j_crafty'},
            {id = 'j_half'},
            {id = 'j_stencil'},
            {id = 'j_four_fingers'},
            --{id = 'j_mime'},
            {id = 'j_credit_card'},
            {id = 'j_ceremonial'},
            {id = 'j_banner'},
            {id = 'j_mystic_summit'},
            {id = 'j_marble'},
            {id = 'j_loyalty_card'},
            {id = 'j_8_ball'},
            {id = 'j_misprint'},
            {id = 'j_dusk'},
            {id = 'j_raised_fist'},
            --{id = 'j_chaos'},
            {id = 'j_fibonacci'},
            {id = 'j_steel_joker'},
            {id = 'j_scary_face'},
            {id = 'j_abstract'},
            {id = 'j_delayed_grat'},
            {id = 'j_hack'},
            {id = 'j_pareidolia'},
            {id = 'j_gros_michel'},
            {id = 'j_even_steven'},
            {id = 'j_odd_todd'},
            {id = 'j_scholar'},
            --{id = 'j_business'},
            {id = 'j_supernova'},
            {id = 'j_ride_the_bus'},
            {id = 'j_space'},
            {id = 'j_egg'},
            --{id = 'j_burglar'},
            {id = 'j_blackboard'},
            {id = 'j_runner'},
            {id = 'j_ice_cream'},
            --{id = 'j_dna'},
            {id = 'j_splash'},
            {id = 'j_blue_joker'},
            {id = 'j_sixth_sense'},
            {id = 'j_constellation'},
            {id = 'j_hiker'},
            {id = 'j_faceless'},
            {id = 'j_green_joker'},
            {id = 'j_superposition'},
            {id = 'j_todo_list'},
            {id = 'j_cavendish'},
            {id = 'j_card_sharp'},
            {id = 'j_red_card'},
            {id = 'j_madness'},
            {id = 'j_square'},
            {id = 'j_seance'},
            --{id = 'j_riff_raff'},
            {id = 'j_vampire'},
            {id = 'j_shortcut'},
            {id = 'j_hologram'},
            {id = 'j_vagabond'},
            --{id = 'j_baron'},
            {id = 'j_cloud_9'},
            --{id = 'j_rocket'},
            {id = 'j_obelisk'},
            {id = 'j_midas_mask'},
            --{id = 'j_luchador'},
            --{id = 'j_photograph'},
            --{id = 'j_gift'},
            --{id = 'j_turtle_bean'},
            {id = 'j_erosion'},
            --{id = 'j_reserved_parking'},
            --{id = 'j_mail'},
            --{id = 'j_to_the_moon'},
            {id = 'j_hallucination'},
            {id = 'j_fortune_teller'},
            --{id = 'j_juggler'},
            {id = 'j_drunkard'},
            {id = 'j_stone'},
            --{id = 'j_golden'},
            {id = 'j_lucky_cat'},
            {id = 'j_baseball'},
            {id = 'j_bull'},
            --{id = 'j_diet_cola'},
            --{id = 'j_trading'},
            {id = 'j_flash'},
            {id = 'j_popcorn'},
            {id = 'j_trousers'},
            {id = 'j_ancient'},
            {id = 'j_ramen'},
            {id = 'j_walkie_talkie'},
            {id = 'j_selzer'},
            {id = 'j_castle'},
            {id = 'j_smiley'},
            {id = 'j_campfire'},
            --{id = 'j_ticket'},
            {id = 'j_mr_bones'},
            {id = 'j_acrobat'},
            --{id = 'j_sock_and_buskin'},
            {id = 'j_swashbuckler'},
            --{id = 'j_troubadour'},
            {id = 'j_certificate'},
            {id = 'j_smeared'},
            {id = 'j_throwback'},
            --{id = 'j_hanging_chad'},
            {id = 'j_rough_gem'},
            --{id = 'j_bloodstone'},
            --{id = 'j_arrowhead'},
            {id = 'j_onyx_agate'},
            {id = 'j_glass'},
            --{id = 'j_ring_master'}, --Showman
            {id = 'j_flower_pot'},
            --{id = 'j_blueprint'},
            {id = 'j_wee'},
            {id = 'j_merry_andy'},
            --{id = 'j_oops'},
            --{id = 'j_idol'},
            {id = 'j_seeing_double'},
            {id = 'j_matador'},
            {id = 'j_hit_the_road'},
            {id = 'j_duo'},
            {id = 'j_trio'},
            {id = 'j_family'},
            {id = 'j_order'},
            {id = 'j_tribe'},
            {id = 'j_stuntman'},
            --{id = 'j_invisible'},
            --{id = 'j_brainstorm'},
            {id = 'j_satellite'},
            {id = 'j_shoot_the_moon'},
            {id = 'j_drivers_license'},
            {id = 'j_cartomancer'},
            {id = 'j_astronomer'},
            {id = 'j_burnt'},
            {id = 'j_bootstraps'},
            {id = 'j_caino'},
            {id = 'j_triboulet'},
            {id = 'j_yorick'},
            {id = 'j_chicot'},
            {id = 'j_perkeo'},
            --- Planet Cards ---
            {id = 'c_mercury'},
            {id = 'c_venus'},
            {id = 'c_earth'},
            --{id = 'c_mars'},
            --{id = 'c_jupiter'},
            {id = 'c_saturn'},
            {id = 'c_uranus'},
            {id = 'c_neptune'},
            --{id = 'c_pluto'},
            {id = 'c_planet_x'},
            {id = 'c_ceres'},
            --{id = 'c_eris'},
            --- Spectral Cards ---
            {id = 'c_familiar'},
            {id = 'c_grim'},
            {id = 'c_incantation'},
            {id = 'c_talisman'},
            {id = 'c_aura'},
            {id = 'c_wraith'},
            {id = 'c_sigil'},
            {id = 'c_ouija'},
            --{id = 'c_ectoplasm'},
            --{id = 'c_immolate'},
            {id = 'c_ankh'},
            --{id = 'c_deja_vu'},
            {id = 'c_hex'},
            {id = 'c_trance'},
            {id = 'c_medium'},
            --{id = 'c_cryptid'},
            {id = 'c_soul'},
            --{id = 'c_black_hole'},
            --- Tags ---
            {id = 'tag_handy'},
            {id = 'tag_standard'},
            {id = 'tag_d_six'},
            --{id = 'tag_negative'},
            --{id = 'tag_investment'},
            {id = 'tag_holo'},
            --{id = 'tag_rare'},
            --{id = 'tag_voucher'},
            {id = 'tag_garbage'},
            {id = 'tag_foil'},
            {id = 'tag_buffoon'},
            --{id = 'tag_boss'},
            --{id = 'tag_ethereal'},
            {id = 'tag_orbital'},
            {id = 'tag_charm'},
            {id = 'tag_skip'},
            {id = 'tag_top_up'},
            {id = 'tag_polychrome'},
            {id = 'tag_juggle'},
            {id = 'tag_double'},
            {id = 'tag_coupon'},
            {id = 'tag_economy'},
            {id = 'tag_uncommon'},
            {id = 'tag_meteor'},
            --- Tarot Cards ---
            --{id = 'c_fool'},
            --{id = 'c_magician'},
            {id = 'c_high_priestess'},
            {id = 'c_empress'},
            --{id = 'c_emperor'},
            {id = 'c_heirophant'},
            {id = 'c_lovers'},
            --{id = 'c_chariot'},
            {id = 'c_justice'},
            --{id = 'c_hermit'},
            {id = 'c_wheel_of_fortune'},
            --{id = 'c_strength'},
            --{id = 'c_hanged_man'},
            --{id = 'c_death'},
            --{id = 'c_temperance'},
            --{id = 'c_devil'},
            {id = 'c_tower'},
            {id = 'c_star'},
            {id = 'c_moon'},
            --{id = 'c_sun'},
            {id = 'c_judgement'},
            --{id = 'c_world'},
            --- Vouchers ---
            --{id = 'v_overstock_norm'},
            --{id = 'v_overstock_plus'},
            --{id = 'v_clearance_sale'},
            --{id = 'v_liquidation'},
            {id = 'v_hone'},
            {id = 'v_glow_up'},
            --{id = 'v_reroll_surplus'},
            --{id = 'v_reroll_glut'},
            --{id = 'v_crystal_ball'},
            --{id = 'v_omen_globe'},
            --{id = 'v_telescope'},
            {id = 'v_observatory'},
            --{id = 'v_grabber'},
            --{id = 'v_nacho_tong'},
            --{id = 'v_wasteful'},
            --{id = 'v_recyclomancy'},
            {id = 'v_tarot_merchant'},
            {id = 'v_tarot_tycoon'},
            {id = 'v_planet_merchant'},
            {id = 'v_planet_tycoon'},
            --{id = 'v_seed_money'},
            --{id = 'v_money_tree'},
            --{id = 'v_blank'},
            --{id = 'v_antimatter'},
            --{id = 'v_magic_trick'},
            --- BREAK HERE ---
            {id = 'v_illusion'}
            --{id = 'v_hieroglyph'},
            --{id = 'v_petroglyph'},
            --{id = 'v_directors_cut'},
            --{id = 'v_retcon'},
            --{id = 'v_paint_brush'},
            --{id = 'v_palette'},
        },
        ante_scaling = 2,
        plasma_balancing = true
    },
    -- Blank cardback
    {x = 1, y = 0},
    {
        ["name"]="naneinf+ Deck",
        ["text"]={
            [1]="Balance {C:chips}Chips{} and {C:mult}Mult{} when calculating",
            [2]="score for played hand | {C:red}X2{} base Blind size",
            [3]="{X:mult,C:white}ALMOST {X:mult,C:white}ALL{} \"useless\"",
            [4]="{C:uncommon}Jokers{}, {C:tarot}Consumables{}, {C:attention}Tags{} and {C:attention}Vouchers{}",
            [5]="are banned, easing unseeded naneinf practice"
        }
    }
)
naneinfplus:register()

------------ NANEINF- DECK ------------

local naneinfminus = SMODS.Deck:new(
    "naneinf- Deck",
    "naneinfminus",
    {
        ban_keys = {
            --- Jokers ---
            {id = 'j_joker'},
            {id = 'j_greedy_joker'},
            {id = 'j_lusty_joker'},
            {id = 'j_wrathful_joker'},
            {id = 'j_gluttenous_joker'},
            {id = 'j_jolly'},
            {id = 'j_zany'},
            {id = 'j_mad'},
            {id = 'j_crazy'},
            {id = 'j_droll'},
            {id = 'j_sly'},
            {id = 'j_wily'},
            {id = 'j_clever'},
            {id = 'j_devious'},
            {id = 'j_crafty'},
            {id = 'j_half'},
            {id = 'j_stencil'},
            {id = 'j_four_fingers'},
            --{id = 'j_mime'},
            --{id = 'j_credit_card'},
            {id = 'j_ceremonial'},
            {id = 'j_banner'},
            {id = 'j_mystic_summit'},
            {id = 'j_marble'},
            {id = 'j_loyalty_card'},
            --{id = 'j_8_ball'},
            {id = 'j_misprint'},
            {id = 'j_dusk'},
            {id = 'j_raised_fist'},
            --{id = 'j_chaos'},
            {id = 'j_fibonacci'},
            {id = 'j_steel_joker'},
            --{id = 'j_scary_face'},
            {id = 'j_abstract'},
            --{id = 'j_delayed_grat'},
            {id = 'j_hack'},
            {id = 'j_pareidolia'},
            {id = 'j_gros_michel'},
            {id = 'j_even_steven'},
            {id = 'j_odd_todd'},
            {id = 'j_scholar'},
            --{id = 'j_business'},
            {id = 'j_supernova'},
            {id = 'j_ride_the_bus'},
            {id = 'j_space'},
            --{id = 'j_egg'},
            --{id = 'j_burglar'},
            {id = 'j_blackboard'},
            {id = 'j_runner'},
            {id = 'j_ice_cream'},
            --{id = 'j_dna'},
            --{id = 'j_splash'},
            {id = 'j_blue_joker'},
            --{id = 'j_sixth_sense'},
            {id = 'j_constellation'},
            {id = 'j_hiker'},
            --{id = 'j_faceless'},
            {id = 'j_green_joker'},
            {id = 'j_superposition'},
            --{id = 'j_todo_list'},
            {id = 'j_cavendish'},
            {id = 'j_card_sharp'},
            {id = 'j_red_card'},
            {id = 'j_madness'},
            {id = 'j_square'},
            {id = 'j_seance'},
            --{id = 'j_riff_raff'},
            {id = 'j_vampire'},
            {id = 'j_shortcut'},
            {id = 'j_hologram'},
            {id = 'j_vagabond'},
            --{id = 'j_baron'},
            {id = 'j_cloud_9'},
            --{id = 'j_rocket'},
            {id = 'j_obelisk'},
            --{id = 'j_midas_mask'},
            --{id = 'j_luchador'},
            --{id = 'j_photograph'},
            --{id = 'j_gift'},
            --{id = 'j_turtle_bean'},
            {id = 'j_erosion'},
            --{id = 'j_reserved_parking'},
            --{id = 'j_mail'},
            --{id = 'j_to_the_moon'},
            --{id = 'j_hallucination'},
            {id = 'j_fortune_teller'},
            --{id = 'j_juggler'},
            --{id = 'j_drunkard'},
            {id = 'j_stone'},
            --{id = 'j_golden'},
            {id = 'j_lucky_cat'},
            {id = 'j_baseball'},
            {id = 'j_bull'},
            --{id = 'j_diet_cola'},
            --{id = 'j_trading'},
            {id = 'j_flash'},
            {id = 'j_popcorn'},
            {id = 'j_trousers'},
            {id = 'j_ancient'},
            {id = 'j_ramen'},
            {id = 'j_walkie_talkie'},
            {id = 'j_selzer'},
            {id = 'j_castle'},
            {id = 'j_smiley'},
            {id = 'j_campfire'},
            --{id = 'j_ticket'},
            --{id = 'j_mr_bones'},
            {id = 'j_acrobat'},
            --{id = 'j_sock_and_buskin'},
            {id = 'j_swashbuckler'},
            --{id = 'j_troubadour'},
            {id = 'j_certificate'},
            {id = 'j_smeared'},
            {id = 'j_throwback'},
            --{id = 'j_hanging_chad'},
            {id = 'j_rough_gem'},
            --{id = 'j_bloodstone'},
            --{id = 'j_arrowhead'},
            {id = 'j_onyx_agate'},
            {id = 'j_glass'},
            --{id = 'j_ring_master'}, --Showman
            {id = 'j_flower_pot'},
            --{id = 'j_blueprint'},
            {id = 'j_wee'},
            --{id = 'j_merry_andy'},
            --{id = 'j_oops'},
            --{id = 'j_idol'},
            {id = 'j_seeing_double'},
            {id = 'j_matador'},
            {id = 'j_hit_the_road'},
            {id = 'j_duo'},
            {id = 'j_trio'},
            {id = 'j_family'},
            {id = 'j_order'},
            {id = 'j_tribe'},
            {id = 'j_stuntman'},
            --{id = 'j_invisible'},
            --{id = 'j_brainstorm'},
            --{id = 'j_satellite'},
            --{id = 'j_shoot_the_moon'},
            {id = 'j_drivers_license'},
            --{id = 'j_cartomancer'},
            --{id = 'j_astronomer'},
            {id = 'j_burnt'},
            {id = 'j_bootstraps'},
            {id = 'j_caino'},
            --{id = 'j_triboulet'},
            {id = 'j_yorick'},
            {id = 'j_chicot'},
            --{id = 'j_perkeo'},
            --- Planet Cards ---
            {id = 'c_mercury'},
            --{id = 'c_venus'},
            {id = 'c_earth'},
            --{id = 'c_mars'},
            --{id = 'c_jupiter'},
            {id = 'c_saturn'},
            {id = 'c_uranus'},
            {id = 'c_neptune'},
            --{id = 'c_pluto'},
            --{id = 'c_planet_x'},
            --{id = 'c_ceres'},
            --{id = 'c_eris'},
            --- Spectral Cards ---
            {id = 'c_familiar'},
            {id = 'c_grim'},
            {id = 'c_incantation'},
            --{id = 'c_talisman'},
            --{id = 'c_aura'},
            {id = 'c_wraith'},
            {id = 'c_sigil'},
            {id = 'c_ouija'},
            --{id = 'c_ectoplasm'},
            --{id = 'c_immolate'},
            --{id = 'c_ankh'},
            --{id = 'c_deja_vu'},
            {id = 'c_hex'},
            {id = 'c_trance'},
            --{id = 'c_medium'},
            --{id = 'c_cryptid'},
            --{id = 'c_soul'},
            --{id = 'c_black_hole'},
            --- Tags ---
            {id = 'tag_handy'},
            {id = 'tag_standard'},
            {id = 'tag_d_six'},
            --{id = 'tag_negative'},
            --{id = 'tag_investment'},
            {id = 'tag_holo'},
            --{id = 'tag_rare'},
            --{id = 'tag_voucher'},
            {id = 'tag_garbage'},
            {id = 'tag_foil'},
            {id = 'tag_buffoon'},
            --{id = 'tag_boss'},
            --{id = 'tag_ethereal'},
            {id = 'tag_orbital'},
            --{id = 'tag_charm'},
            {id = 'tag_skip'},
            {id = 'tag_top_up'},
            {id = 'tag_polychrome'},
            --{id = 'tag_juggle'},
            {id = 'tag_double'},
            {id = 'tag_coupon'},
            {id = 'tag_economy'},
            --{id = 'tag_uncommon'},
            {id = 'tag_meteor'},
            --- Tarot Cards ---
            --{id = 'c_fool'},
            --{id = 'c_magician'},
            {id = 'c_high_priestess'},
            {id = 'c_empress'},
            --{id = 'c_emperor'},
            {id = 'c_heirophant'},
            {id = 'c_lovers'},
            --{id = 'c_chariot'},
            {id = 'c_justice'},
            --{id = 'c_hermit'},
            {id = 'c_wheel_of_fortune'},
            --{id = 'c_strength'},
            --{id = 'c_hanged_man'},
            --{id = 'c_death'},
            --{id = 'c_temperance'},
            --{id = 'c_devil'},
            {id = 'c_tower'},
            {id = 'c_star'},
            {id = 'c_moon'},
            --{id = 'c_sun'},
            --{id = 'c_judgement'},
            --{id = 'c_world'},
            --- Vouchers ---
            --{id = 'v_overstock_norm'},
            --{id = 'v_overstock_plus'},
            --{id = 'v_clearance_sale'},
            --{id = 'v_liquidation'},
            --{id = 'v_hone'},
            --{id = 'v_glow_up'},
            --{id = 'v_reroll_surplus'},
            --{id = 'v_reroll_glut'},
            --{id = 'v_crystal_ball'},
            --{id = 'v_omen_globe'},
            --{id = 'v_telescope'},
            --{id = 'v_observatory'},
            --{id = 'v_grabber'},
            --{id = 'v_nacho_tong'},
            --{id = 'v_wasteful'},
            --{id = 'v_recyclomancy'},
            {id = 'v_tarot_merchant'},
            {id = 'v_tarot_tycoon'},
            {id = 'v_planet_merchant'},
            --- BREAK HERE ---
            {id = 'v_planet_tycoon'}
            --{id = 'v_seed_money'},
            --{id = 'v_money_tree'},
            --{id = 'v_blank'},
            --{id = 'v_antimatter'},
            --{id = 'v_magic_trick'},
            --{id = 'v_illusion'}
            --{id = 'v_hieroglyph'},
            --{id = 'v_petroglyph'},
            --{id = 'v_directors_cut'},
            --{id = 'v_retcon'},
            --{id = 'v_paint_brush'},
            --{id = 'v_palette'},
        },
        ante_scaling = 2,
        plasma_balancing = true
    },
    -- Plasma cardback
    {x = 4, y = 2},
    {
        ["name"]="naneinf- Deck",
        ["text"]={
            [1]="Balance {C:chips}Chips{} and {C:mult}Mult{} when calculating",
            [2]="score for played hand | {C:red}X2{} base Blind size",
            [3]="{C:purple}Minimal{} \"useless\"",
            [4]="{C:uncommon}Jokers{}, {C:tarot}Consumables{}, {C:attention}Tags{} and {C:attention}Vouchers{}",
            [5]="are banned, easing unseeded naneinf practice"
        }
    }
)
naneinfminus:register()

----------------------------------------------
------------MOD CODE END----------------------
